version: '3.8'

services:
  mrroboto:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mrroboto-bot
    restart: unless-stopped
    
    # Environment variables for testing (without .env file initially)
    environment:
      - NODE_ENV=production
      - TZ=UTC
      - LOG_LEVEL=info
    
    # Mount volumes for persistent data
    volumes:
      # Persistent storage for data.json (bot's memory)
      - ./data.json:/usr/src/app/data.json
      # Persistent storage for logs
      - ./logs:/usr/src/app/logs
    
    # Resource limits to prevent runaway processes
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Network configuration
    networks:
      - mrroboto-network
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Networks
networks:
  mrroboto-network:
    driver: bridge

# Volumes (if you prefer named volumes instead of bind mounts)
volumes:
  mrroboto-data:
    driver: local
  mrroboto-logs:
    driver: local